CREATE DEFINER = 'utest'@'%'
PROCEDURE qxyybak.SYNC_DATA_QSYY2LEYA_PATIENT_PRO(in patientID varchar(40),OUT resultVal VARCHAR(2))
BEGIN
  DECLARE SQL_ERROR_FLAG INTEGER DEFAULT 0;
  DECLARE autocommit INTEGER DEFAULT 0;
   DECLARE ROLE_CODE varchar(30);
   DECLARE LOGIN_MOBILE_TEMP varchar(30);
   DECLARE MEMBER_COUNT INT DEFAULT 0;
   DECLARE PATIENT_COUNT INT DEFAULT 0;
   DECLARE MOBILE_COUNT INT DEFAULT 0;
   DECLARE ADDRESS_COUNT INT DEFAULT 0;
   DECLARE LEYA_LOGINUSER_MASTER_ID CHAR(32);
   DECLARE LEYA_CUSTOMER_ID CHAR(32);
   DECLARE LEYA_CERT_TYPE VARCHAR (10);
   DECLARE INSTITUTION_MARK VARCHAR(3) DEFAULT 'no';
   DECLARE MEMBER_MARK INT DEFAULT 9;
   DECLARE MEMBERID VARCHAR(255);
   DECLARE INSTITUTIONID varchar(40);

   DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET SQL_ERROR_FLAG = 1;
   SET autocommit = 0;

SELECT
    rt.ROLE_CODE
INTO ROLE_CODE FROM
    `newzhuce`.role_type rt
WHERE
    rt.ROLE_VALUE = 'MEMBER';


SELECT
    lti.LOGIN_TYPE_CODE
INTO LOGIN_MOBILE_TEMP FROM
    `newzhuce`.login_type_item lti
WHERE
    lti.LOGIN_TYPE_VALUE = 'MOBILE';
	SELECT C_MEMBER_ID
	into MEMBERID
	FROM mem_patient_bak
	WHERE ID=patientID;
	select INSTITUTION_ID
	into INSTITUTIONID
	from qsyy_blh
	where MEMBER_ID=MEMBERID
	and PATIENT_ID=patientID;


    SELECT qs.is_LATENT
    INTO INSTITUTION_MARK
    FROM
      qsyy_register qr,
      qsyy_switch qs
    WHERE
      qr.CLIENT_ID=INSTITUTIONID
      AND qr.ID = qs.QSYY_REGISTER_ID;


	SELECT
		COUNT(ID)
		INTO MEMBER_COUNT FROM
		`newzhuce`.mem_member
	WHERE
		ID = MEMBERID;

	SELECT
		@P_CREATE_DATE:=C_CREATE_DATE,
		@P_DELETE_FLAG:=C_DELETE_FLAG,
		@M_MOBILE:=C_MOBILE,
		@M_SEX:=C_SEX,
		@M_ADDRESS:=C_ADDRESS,
		@M_BIRTHDAY:=C_BIRTHDATE,
		@M_IDCARD:=C_ID_CARD,
		@M_C_NAME:=`C_NAME`,
		@M_C_MEMBER_ID:=C_MEMBER_ID
	FROM
		mem_patient_bak
	WHERE
		id = patientID;

	select
		@MM_C_CREATE_DATE:=C_CREATE_DATE,
		@MM_C_DELETE_FLAG:=C_DELETE_FLAG,
		@MM_C_ADDRESS:=C_ADDRESS,
		@MM_C_LEVEL:=C_LEVEL,
		@MM_C_STATUS:=C_STATUS,
		@MM__C_MEMBER_ID:=C_MEMBER_ID
	from mem_member_bak
	where ID=MEMBERID;


	IF MEMBER_COUNT = 0 THEN
		SELECT c.ID INTO LEYA_CUSTOMER_ID FROM `newzhuce`.customer c WHERE c.NAME = @M_C_NAME AND c.CERT_TYPE = '1' AND c.CERT_NO = @M_IDCARD AND c.SEX = @M_SEX AND c.BIRTHDAY = @M_BIRTHDAY;
		/*IF(ISNULL(@M_IDCARD) <> 1 && LENGTH(@M_IDCARD )>=1 && @M_IDCARD  <> 'null') THEN
			SET  LEYA_CERT_TYPE='1';
		END IF;
		IF(ISNULL(LEYA_CUSTOMER_ID) = 1 || LENGTH(LEYA_CUSTOMER_ID) = 0 ||  LEYA_CUSTOMER_ID = 'null') THEN
			SET LEYA_CUSTOMER_ID = sys_guid();
			INSERT INTO `newzhuce`.customer (ID,`NAME`,CERT_TYPE,CERT_NO,SEX,BIRTHDAY,CREATE_DATE,UPDATE_DATE) VALUES (LEYA_CUSTOMER_ID,@M_C_NAME,LEYA_CERT_TYPE,@M_IDCARD,
					@M_SEX,
					@M_BIRTHDAY,
					@P_CREATE_DATE,
					@P_CREATE_DATE
					);
		END IF;*/

		SELECT
		ID
		INTO LEYA_LOGINUSER_MASTER_ID FROM
			`newzhuce`.login_user_master
		WHERE
			CUSTOMER_ID = LEYA_CUSTOMER_ID
		LIMIT 1;
		/*IF(LENGTH(LEYA_LOGINUSER_MASTER_ID) = 0 || ISNULL(LEYA_LOGINUSER_MASTER_ID) = 1) THEN
		   SET LEYA_LOGINUSER_MASTER_ID=sys_guid();
		   	*//*IF(LCASE(INSTITUTION_MARK)='yes') THEN
					SET MEMBER_MARK=0;
				ELSE
        *//**//*IF(ISNULL(@M_MOBILE) <> 1 && LENGTH(@M_MOBILE)>=1 && @M_MOBILE  <> 'null') THEN
					SELECT @QIANZAIKEHU:=lum.qianzaikehu,@OLDMASTERID:=lum.id FROM `newzhuce`.login_user_expand ex,newzhuce.`login_user_master` lum WHERE ex.`LOGIN_USER_MASTER_ID`=lum.`ID` AND ex.EXPAND_VALUE=@M_MOBILE AND e.EXPAND_STATUS = 0 AND ex.LOGIN_TYPE_CODE = LOGIN_MOBILE_TEMP limit 1;
				  	*//**//**//**//*IF (ISNULL(@QIANZAIKEHU)<>1 && LENGTH(@QIANZAIKEHU)>=1 &&@QIANZAIKEHU<>'null')THEN
							*//**//**//**//**//**//**//**//*IF(@QIANZAIKEHU=0)THEN
								SET MEMBER_MARK=1;
						  ELSE
								SET MEMBER_MARK=0;
							END IF ;*//**//**//**//**//**//**//**//*
						ELSE
					  SET MEMBER_MARK=1;
					  END IF ;*//**//**//**//*
			END IF;*//**//*
        END IF;*//*
		*//*IF(MEMBER_MARK<>9)THEN
			INSERT INTO `newzhuce`.login_user_master (
					ID,
					LOGIN_ACCOUNT,
					LOGIN_PASSWORD,
					LOGIN_STATUS,
					LOGIN_LAST_TIME,
					LOGIN_COUNT,
					SOURCE_IDENTITY,
					CUSTOMER_ID,
					QIANZAIKEHU,
					TONGDAOLAIYUAN,
					SHUJULAIYUAN
					) VALUES (
					LEYA_LOGINUSER_MASTER_ID,
					@C_ACCOUNT,
					@C_PASSWORD,
					0,
					@P_CREATE_DATE,
					0,
					'QSYY',
					LEYA_CUSTOMER_ID,
					MEMBER_MARK,
					'LYWBJK',
					'QSYY'
					);
		END IF;*//*

		Insert INTO `newzhuce`.MEM_SUOSHU_MENZHENG (ID,LOGUSER_MASTER_ID,INSTITUTION_ID) VALUES (sys_guid(),LEYA_LOGINUSER_MASTER_ID,INSTITUTIONID);
		Insert INTO `newzhuce`.USER_RELATION_ROLE (ID,LOGIN_USER_MASTER_ID,ROLE_CODE,ROLE_STATUS) VALUES (sys_guid(),LEYA_LOGINUSER_MASTER_ID,ROLE_CODE,0);
		END IF;*/
		/*IF(ISNULL(@M_MOBILE) <> 1 && LENGTH(@M_MOBILE)>=1 && @M_MOBILE  <> 'null') THEN
		  		SELECT COUNT(ex.ID) into MOBILE_COUNT FROM `newzhuce`.login_user_expand ex
          WHERE ex.LOGIN_USER_MASTER_ID =LEYA_LOGINUSER_MASTER_ID AND ex.EXPAND_STATUS = 0 AND ex.LOGIN_TYPE_CODE = LOGIN_MOBILE_TEMP;
			*//*IF MOBILE_COUNT <> 0 THEN
			    UPDATE `newzhuce`.login_user_expand SET EXPAND_VALUE=@M_MOBILE WHERE LOGIN_USER_MASTER_ID=LEYA_LOGINUSER_MASTER_ID;
					UPDATE `newzhuce`.customer_contact_telphone
				SET
					PHONE_NUMBER = @M_MOBILE
				WHERE
					CUSTOMER_ID = LEYA_CUSTOMER_ID
						AND PHONE_TYPE = 9;
			ELSE
				INSERT INTO `newzhuce`.login_user_expand (ID,LOGIN_USER_MASTER_ID,LOGIN_TYPE_CODE,EXPAND_VALUE,EXPAND_STATUS,EXPAND_SORT) VALUES (sys_guid(),LEYA_LOGINUSER_MASTER_ID,LOGIN_MOBILE_TEMP,@M_MOBILE,0,1);
				INSERT INTO `newzhuce`.customer_contact_telphone (ID,CUSTOMER_ID,PHONE_NUMBER,PHONE_STATUS,PHONE_TYPE) VALUES (sys_guid(),LEYA_CUSTOMER_ID,@M_MOBILE,0,9);
		    END IF;*//*
		END IF;*/
		/*IF(ISNULL(@M_ADDRESS) <> 1 && LENGTH(@M_ADDRESS)>=1 && @M_ADDRESS  <> 'null') THEN
		   SELECT COUNT(CA.ID) into ADDRESS_COUNT FROM `newzhuce`.customer_address CA WHERE  CA.ADDRESS_TYPE =9 AND CA.CUSTOMER_ID=LEYA_CUSTOMER_ID;
				IF ADDRESS_COUNT <> 0 THEN
			    UPDATE `newzhuce`.customer_address SET ADDRESS_DETAIL=@M_ADDRESS WHERE CUSTOMER_ID=LEYA_CUSTOMER_ID;
				ELSE
					INSERT INTO `newzhuce`.customer_address (ID,CUSTOMER_ID,ADDRESS_TYPE,ADDRESS_STATUS,ADDRESS_DETAIL) VALUES (sys_guid(),LEYA_CUSTOMER_ID,9,0,@M_ADDRESS);
		    END IF;
	    END IF;*/

    /*SELECT @M_MEMBER_ID:=id FROM `newzhuce`.mem_member WHERE CUSTOMER_ID=LEYA_CUSTOMER_ID;
		IF(ISNULL(@M_MEMBER_ID)<>1 && LENGTH(@M_MEMBER_ID)>=0 && @M_MEMBER_ID<>'null')THEN
			IF(@M_MEMBER_ID<>MEMBERID)THEN
			SELECT @OLD_MEMBER_ID:=id FROM mem_member_bak WHERE id=@M_MEMBER_ID;
			IF(ISNULL(@OLD_MEMBER_ID)<>1 && LENGTH(@OLD_MEMBER_ID)>=0 && @OLD_MEMBER_ID<>'null')THEN
				UPDATE mem_patient_bak SET C_MEMBER_ID=@OLD_MEMBER_ID WHERE ID=patientID;
				UPDATE qsyy_blh SET MEMBER_ID=@OLD_MEMBER_ID WHERE INSTITUTION_ID=INSTITUTIONID AND MEMBER_ID=MEMBERID AND PATIENT_ID=patientID;
				set MEMBERID=@OLD_MEMBER_ID;
			ELSE
				UPDATE mem_patient_bak SET C_MEMBER_ID=@M_MEMBER_ID WHERE ID=patientID;
				UPDATE qsyy_blh SET MEMBER_ID=@M_MEMBER_ID WHERE INSTITUTION_ID=INSTITUTIONID AND MEMBER_ID=MEMBERID AND PATIENT_ID=patientID;
				UPDATE mem_member_bak SET id=@M_MEMBER_ID WHERE ID = MEMBERID;
				set MEMBERID=@M_MEMBER_ID;
				END IF;
			END IF;
				ELSE
        	Insert INTO `newzhuce`.mem_member(ID,C_CREATE_DATE,C_DELETE_FLAG,C_ADDRESS,C_LEVEL,C_STATUS,C_MEMBER_ID,CUSTOMER_ID) values(MEMBERID,@MM_C_CREATE_DATE,@MM_C_DELETE_FLAG,@MM_C_ADDRESS,@MM_C_LEVEL,@MM_C_STATUS,@MM_C_MEMBER_ID,LEYA_CUSTOMER_ID);
        END IF;*/
	END IF;

	SELECT
		COUNT(ID)
	INTO PATIENT_COUNT FROM
		`newzhuce`.mem_patient
	WHERE
		ID = patientID;
	IF PATIENT_COUNT <> 0 THEN
		IF(ISNULL(@M_MOBILE) <> 1 && LENGTH(@M_MOBILE)>=1 && @M_MOBILE  <> 'null') THEN
	     UPDATE `newzhuce`.mem_patient SET C_MOBILE=@M_MOBILE WHERE ID=patientID;
	    END IF;
		UPDATE `newzhuce`.mem_patient
		SET
			C_NAME = @M_C_NAME,
			C_SEX = @M_SEX,
			C_BIRTHDATE = @M_BIRTHDAY,
			C_ID_CARD = @M_IDCARD,
			C_ADDRESS = @M_ADDRESS
		WHERE
    ID = patientID;
    ELSE
     INSERT INTO `newzhuce`.mem_patient(ID,C_CREATE_DATE,C_DELETE_FLAG,C_NAME,C_SEX,C_BIRTHDATE,C_ID_CARD,C_MOBILE,C_ADDRESS,C_MEMBER_ID)
		VALUES (patientID,@P_CREATE_DATE,@P_DELETE_FLAG,@M_C_NAME,@,@M_BIRTHDAY,@M_IDCARD,@M_MOBILE,@M_ADDRESS,@M_C_MEMBER_ID);
   END IF;
	ELSE

	 SET SQL_ERROR_FLAG=1;
	UPDATE mem_patient_bak
SET
    `SYNC` = 2,
    `SYNCTIME` = NOW()
WHERE
    ID = patientID;
	END IF;

  IF(SQL_ERROR_FLAG <> 1) then
  IF(ISNULL(patientID) <> 1 && LENGTH(patientID)>=1 && patientID <> 'null') THEN
	UPDATE mem_patient_bak
SET
    `SYNC` = 1,
    `SYNCTIME` = NOW()
WHERE
    ID = patientID;
  END IF;
	SET resultVal = '0';
    COMMIT;
  ELSE
    SET resultVal = '1';
    ROLLBACK;
	IF(ISNULL(patientID) <> 1 && LENGTH(patientID)>=1 && patientID <> 'null') THEN
	UPDATE mem_patient_bak
SET
    `SYNC` = 2,
    `SYNCTIME` = NOW()
WHERE
    ID = patientID;
	 commit;
  END IF;
  END IF;
END
